"""
Event-driven backtesting engine for QuantVortex.

Supports multi-asset, multi-strategy backtesting with realistic
slippage and commission modelling through an event-driven loop.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class EventType(Enum):
    """Enumeration of event types in the backtesting loop."""
    MARKET = auto()
    SIGNAL = auto()
    ORDER = auto()
    FILL = auto()


class OrderDirection(Enum):
    """Direction of a trade order."""
    BUY = 1
    SELL = -1


# ---------------------------------------------------------------------------
# Event dataclasses
# ---------------------------------------------------------------------------

@dataclass
class MarketEvent:
    """
    Represents the arrival of new market data.

    Parameters
    ----------
    timestamp : datetime
        The bar's timestamp.
    symbol : str
        The asset ticker/symbol.
    open : float
        Bar open price.
    high : float
        Bar high price.
    low : float
        Bar low price.
    close : float
        Bar close price.
    volume : float
        Bar volume.
    """

    timestamp: datetime
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    event_type: EventType = field(default=EventType.MARKET, init=False)


@dataclass
class SignalEvent:
    """
    Represents a trading signal generated by a strategy.

    Parameters
    ----------
    timestamp : datetime
        Time the signal was generated.
    symbol : str
        Target asset symbol.
    target_weight : float
        Desired portfolio weight, in [-1, 1].
    strategy_id : str
        Identifier of the originating strategy.
    """

    timestamp: datetime
    symbol: str
    target_weight: float
    strategy_id: str = "default"
    event_type: EventType = field(default=EventType.SIGNAL, init=False)


@dataclass
class OrderEvent:
    """
    Represents an order to be sent to the (simulated) broker.

    Parameters
    ----------
    timestamp : datetime
        Time the order was placed.
    symbol : str
        Target asset symbol.
    quantity : float
        Number of shares/units (positive = buy, negative = sell).
    order_type : str
        ``"MKT"`` for market order (only type currently supported).
    direction : OrderDirection
        BUY or SELL.
    """

    timestamp: datetime
    symbol: str
    quantity: float
    order_type: str
    direction: OrderDirection
    event_type: EventType = field(default=EventType.ORDER, init=False)


@dataclass
class FillEvent:
    """
    Represents the execution of an order.

    Parameters
    ----------
    timestamp : datetime
        Time the fill occurred.
    symbol : str
        Filled asset symbol.
    quantity : float
        Filled quantity (positive = long, negative = short).
    fill_price : float
        Actual execution price after slippage.
    commission : float
        Commission charged for the trade.
    direction : OrderDirection
        BUY or SELL.
    """

    timestamp: datetime
    symbol: str
    quantity: float
    fill_price: float
    commission: float
    direction: OrderDirection
    event_type: EventType = field(default=EventType.FILL, init=False)

    @property
    def trade_value(self) -> float:
        """Gross trade value (price × quantity, unsigned)."""
        return abs(self.quantity) * self.fill_price

    @property
    def net_cost(self) -> float:
        """
        Signed net cost of the fill including commission.

        Positive means cash outflow (buy), negative means cash inflow (sell).
        """
        sign = 1.0 if self.direction == OrderDirection.BUY else -1.0
        return sign * abs(self.quantity) * self.fill_price + self.commission


# ---------------------------------------------------------------------------
# BacktestEngine
# ---------------------------------------------------------------------------

class BacktestEngine:
    """
    Event-driven backtesting engine for multi-asset, multi-strategy portfolios.

    Parameters
    ----------
    initial_capital : float, optional
        Starting cash balance in base currency. Default is ``10_000_000``.
    commission_bps : float, optional
        Round-trip commission in basis points applied per trade. Default is ``5.0``.
    slippage_bps : float, optional
        One-way slippage in basis points applied at fill. Default is ``10.0``.

    Examples
    --------
    >>> engine = BacktestEngine(initial_capital=1_000_000)
    >>> equity = engine.run(price_data, positions)
    >>> trade_log = engine.get_trade_log()
    """

    def __init__(
        self,
        initial_capital: float = 10_000_000,
        commission_bps: float = 5.0,
        slippage_bps: float = 10.0,
    ) -> None:
        if initial_capital <= 0:
            raise ValueError(f"initial_capital must be positive, got {initial_capital}")
        if commission_bps < 0:
            raise ValueError(f"commission_bps must be non-negative, got {commission_bps}")
        if slippage_bps < 0:
            raise ValueError(f"slippage_bps must be non-negative, got {slippage_bps}")

        self.initial_capital: float = initial_capital
        self.commission_bps: float = commission_bps
        self.slippage_bps: float = slippage_bps

        self._fills: List[FillEvent] = []
        self._event_queue: List[object] = []

        logger.info(
            "BacktestEngine initialised | capital=%.2f commission_bps=%.1f slippage_bps=%.1f",
            initial_capital,
            commission_bps,
            slippage_bps,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(
        self,
        price_data: pd.DataFrame,
        positions: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Execute the backtest over the supplied price and position data.

        Parameters
        ----------
        price_data : pd.DataFrame
            OHLCV data with a ``DatetimeIndex`` and columns:
            ``[symbol]_open``, ``[symbol]_high``, ``[symbol]_low``,
            ``[symbol]_close``, ``[symbol]_volume`` **or** a simple
            multi-level column DataFrame with level-0 = field,
            level-1 = symbol.  Also accepts a single-symbol DataFrame
            with columns ``open``, ``high``, ``low``, ``close``, ``volume``.
        positions : pd.DataFrame
            Target portfolio weights aligned to ``price_data``'s index.
            Columns are asset symbols, values are weights in ``[-1, 1]``.
            Rebalancing is assumed to occur at the *next* open price to
            avoid look-ahead bias.

        Returns
        -------
        pd.DataFrame
            Portfolio equity curve with columns ``equity``, ``cash``,
            ``holdings``, and ``returns``.

        Raises
        ------
        ValueError
            If ``price_data`` or ``positions`` are empty, or if their
            indices do not overlap.
        """
        self._validate_inputs(price_data, positions)
        self._fills = []

        price_data, positions = self._align_data(price_data, positions)
        close_prices = self._extract_close(price_data)
        open_prices = self._extract_open(price_data)
        symbols = close_prices.columns.tolist()

        logger.info(
            "Starting backtest | dates=%d symbols=%d",
            len(price_data),
            len(symbols),
        )

        # State
        cash: float = self.initial_capital
        current_holdings: Dict[str, float] = {s: 0.0 for s in symbols}
        equity_records: List[Dict] = []

        dates = price_data.index.tolist()

        for i, date in enumerate(dates):
            # ----------------------------------------------------------
            # 1. Market event: compute current holdings value at close
            # ----------------------------------------------------------
            holdings_value: float = sum(
                current_holdings[s] * close_prices.loc[date, s]
                for s in symbols
            )
            portfolio_value: float = cash + holdings_value
            daily_return: float = 0.0

            if i > 0:
                prev_equity = equity_records[-1]["equity"]
                daily_return = (
                    (portfolio_value - prev_equity) / prev_equity
                    if prev_equity != 0
                    else 0.0
                )

            equity_records.append(
                {
                    "date": date,
                    "equity": portfolio_value,
                    "cash": cash,
                    "holdings": holdings_value,
                    "returns": daily_return,
                }
            )

            # ----------------------------------------------------------
            # 2. Signal / Order / Fill at *next* open to avoid look-ahead
            # ----------------------------------------------------------
            if i + 1 >= len(dates):
                continue  # No next bar to trade on

            next_date = dates[i + 1]
            target_weights = positions.loc[date] if date in positions.index else None

            if target_weights is None:
                continue

            # Determine execution prices (next open)
            exec_prices: Dict[str, float] = {}
            for s in symbols:
                if s in open_prices.columns:
                    raw_px = open_prices.loc[next_date, s]
                    exec_prices[s] = float(raw_px) if not np.isnan(raw_px) else float(close_prices.loc[date, s])
                else:
                    exec_prices[s] = float(close_prices.loc[date, s])

            # Rebalance to target weights
            target_portfolio_value = portfolio_value  # value used for sizing

            for s in symbols:
                target_w = float(target_weights.get(s, 0.0))
                target_w = max(-1.0, min(1.0, target_w))  # clamp

                target_qty = (
                    (target_w * target_portfolio_value) / exec_prices[s]
                    if exec_prices[s] > 0
                    else 0.0
                )
                delta_qty = target_qty - current_holdings[s]

                if abs(delta_qty) < 1e-8:
                    continue  # negligible trade

                direction = OrderDirection.BUY if delta_qty > 0 else OrderDirection.SELL

                # Create order event
                order = OrderEvent(
                    timestamp=next_date,
                    symbol=s,
                    quantity=abs(delta_qty),
                    order_type="MKT",
                    direction=direction,
                )

                # Fill order
                fill = self._fill_order(order, exec_prices[s])
                self._fills.append(fill)

                # Update holdings and cash
                signed_qty = delta_qty
                current_holdings[s] += signed_qty
                cash -= fill.net_cost

        equity_df = pd.DataFrame(equity_records).set_index("date")
        equity_df.index = pd.DatetimeIndex(equity_df.index)

        logger.info(
            "Backtest complete | final_equity=%.2f total_fills=%d",
            equity_df["equity"].iloc[-1] if len(equity_df) else 0.0,
            len(self._fills),
        )
        return equity_df

    def get_trade_log(self) -> pd.DataFrame:
        """
        Return all fill events as a tidy DataFrame.

        Returns
        -------
        pd.DataFrame
            DataFrame with columns: ``timestamp``, ``symbol``, ``direction``,
            ``quantity``, ``fill_price``, ``commission``, ``trade_value``,
            ``net_cost``.  Empty DataFrame if no fills were recorded.
        """
        if not self._fills:
            logger.warning("get_trade_log called with no fills recorded.")
            return pd.DataFrame(
                columns=[
                    "timestamp", "symbol", "direction", "quantity",
                    "fill_price", "commission", "trade_value", "net_cost",
                ]
            )

        records = [
            {
                "timestamp": f.timestamp,
                "symbol": f.symbol,
                "direction": f.direction.name,
                "quantity": f.quantity,
                "fill_price": f.fill_price,
                "commission": f.commission,
                "trade_value": f.trade_value,
                "net_cost": f.net_cost,
            }
            for f in self._fills
        ]
        df = pd.DataFrame(records).set_index("timestamp")
        df.index = pd.DatetimeIndex(df.index)
        return df

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _fill_order(self, order: OrderEvent, raw_price: float) -> FillEvent:
        """
        Simulate filling an order with slippage and commission.

        Parameters
        ----------
        order : OrderEvent
            The order to fill.
        raw_price : float
            Mid-market execution price before slippage.

        Returns
        -------
        FillEvent
            Completed fill with adjusted price and commission.
        """
        fill_price = self._apply_slippage(
            raw_price, order.direction.value, self.slippage_bps
        )
        trade_value = fill_price * order.quantity
        commission = self._compute_commission(trade_value, self.commission_bps)

        return FillEvent(
            timestamp=order.timestamp,
            symbol=order.symbol,
            quantity=order.quantity,
            fill_price=fill_price,
            commission=commission,
            direction=order.direction,
        )

    def _compute_equity_curve(
        self,
        fills: List[FillEvent],
        price_data: pd.DataFrame,
    ) -> pd.Series:
        """
        Reconstruct an equity curve from a list of fills and price data.

        Parameters
        ----------
        fills : list of FillEvent
            Ordered list of fill events.
        price_data : pd.DataFrame
            Close prices indexed by date, one column per symbol.

        Returns
        -------
        pd.Series
            Daily equity values indexed by date.
        """
        close_prices = self._extract_close(price_data)
        symbols = close_prices.columns.tolist()
        holdings: Dict[str, float] = {s: 0.0 for s in symbols}
        cash = self.initial_capital

        fill_idx = 0
        sorted_fills = sorted(fills, key=lambda f: f.timestamp)
        equity_series: Dict[datetime, float] = {}

        for date in close_prices.index:
            # Apply fills that occurred on this date
            while fill_idx < len(sorted_fills) and sorted_fills[fill_idx].timestamp <= date:
                f = sorted_fills[fill_idx]
                sign = 1.0 if f.direction == OrderDirection.BUY else -1.0
                if f.symbol in holdings:
                    holdings[f.symbol] += sign * f.quantity
                cash -= f.net_cost
                fill_idx += 1

            holdings_value = sum(
                holdings.get(s, 0.0) * close_prices.loc[date, s] for s in symbols
            )
            equity_series[date] = cash + holdings_value

        return pd.Series(equity_series)

    @staticmethod
    def _apply_slippage(price: float, direction: int, slippage_bps: float) -> float:
        """
        Adjust a price for one-way market impact/slippage.

        Parameters
        ----------
        price : float
            Mid-market price.
        direction : int
            +1 for a buy (price moves adversely upward),
            -1 for a sell (price moves adversely downward).
        slippage_bps : float
            One-way slippage in basis points.

        Returns
        -------
        float
            Adjusted fill price.
        """
        adjustment = 1.0 + direction * slippage_bps / 10_000.0
        return price * adjustment

    @staticmethod
    def _compute_commission(trade_value: float, commission_bps: float) -> float:
        """
        Calculate the commission for a trade.

        Parameters
        ----------
        trade_value : float
            Gross notional value of the trade (price × quantity).
        commission_bps : float
            Commission rate in basis points.

        Returns
        -------
        float
            Commission amount in base currency.
        """
        return abs(trade_value) * commission_bps / 10_000.0

    # ------------------------------------------------------------------
    # Input validation and data helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _validate_inputs(price_data: pd.DataFrame, positions: pd.DataFrame) -> None:
        """Raise ``ValueError`` if inputs are invalid."""
        if price_data.empty:
            raise ValueError("price_data is empty.")
        if positions.empty:
            raise ValueError("positions is empty.")
        if not isinstance(price_data.index, pd.DatetimeIndex):
            raise ValueError("price_data must have a DatetimeIndex.")
        if not isinstance(positions.index, pd.DatetimeIndex):
            raise ValueError("positions must have a DatetimeIndex.")
        overlap = price_data.index.intersection(positions.index)
        if len(overlap) == 0:
            raise ValueError("price_data and positions have no overlapping dates.")

    @staticmethod
    def _align_data(
        price_data: pd.DataFrame,
        positions: pd.DataFrame,
    ) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """Align price_data and positions to a common sorted DatetimeIndex."""
        common_idx = price_data.index.intersection(positions.index).sort_values()
        return price_data.loc[common_idx], positions.loc[common_idx]

    @staticmethod
    def _extract_close(price_data: pd.DataFrame) -> pd.DataFrame:
        """
        Extract close prices from various DataFrame formats.

        Supports:
        * Multi-level columns with level-0 ``close`` and level-1 symbol.
        * Flat columns named ``<symbol>_close``.
        * A single-symbol DataFrame with a ``close`` column.
        """
        if isinstance(price_data.columns, pd.MultiIndex):
            return price_data.xs("close", axis=1, level=0)

        close_cols = [c for c in price_data.columns if str(c).lower().endswith("_close")]
        if close_cols:
            renamed = {c: c[: -len("_close")] for c in close_cols}
            return price_data[close_cols].rename(columns=renamed)

        if "close" in price_data.columns:
            return price_data[["close"]].rename(columns={"close": "asset"})

        raise ValueError(
            "Cannot extract close prices from price_data. "
            "Expected MultiIndex columns, '<symbol>_close' columns, or a 'close' column."
        )

    @staticmethod
    def _extract_open(price_data: pd.DataFrame) -> pd.DataFrame:
        """
        Extract open prices from various DataFrame formats.

        Falls back to an empty DataFrame if open prices are unavailable.
        """
        try:
            if isinstance(price_data.columns, pd.MultiIndex):
                return price_data.xs("open", axis=1, level=0)

            open_cols = [c for c in price_data.columns if str(c).lower().endswith("_open")]
            if open_cols:
                renamed = {c: c[: -len("_open")] for c in open_cols}
                return price_data[open_cols].rename(columns=renamed)

            if "open" in price_data.columns:
                return price_data[["open"]].rename(columns={"open": "asset"})
        except (KeyError, TypeError):
            pass

        return pd.DataFrame(index=price_data.index)
